### ISSUE TITLE
When will we host the hackathon?

### ISSUE THREAD

**Issue by jackivan88** [seoul-christian-school/hackathon-one#1]
We need to remember the following when considering a date:

- The hackathon date must not conflict with another school event and must be approved by Miss Walker; 
- All TECH class members must attend the hackathon; and
- The hackathon must take place by the end of third quarter.

So what dates look promising?

**Comment by Paul-I** [comment]
3/19/2016

**Comment by jackivan88** [comment]
Did we get confirmation from Miss Walker?

**Comment by brighton818** [comment]
Yes we did
