### ISSUE TITLE
What equipment will participants need?

### ISSUE THREAD

**Issue by jackivan88** [seoul-christian-school/hackathon-one#10]
We need to make sure we indicate clearly what we expect attendees to bring. Do they need a computer? If not, will we provide one for any events that require one? Will there be activities for people who might only have a smartphone?

**Comment by brighton818** [comment]
They should bring their own computers. If there is a certain program needed, they should install it in advance.

**Comment by jackivan88** [comment]
How will we make sure they're able to install the software in advance?
Also, how will we handle if people don't install the software? Will there
be someone available to help them when they arrive?

**Comment by brighton818** [comment]
We will post the list on the facebook if people need to download something.
