### ISSUE TITLE
Do we need some additional stretch projects for other students to complete?

### ISSUE THREAD

**Issue by jackivan88** [seoul-christian-school/hackathon-one#11]
Will we need to create additional stretch projects so that other TECH students can help manage specific parts of the hackathon or lead certain events?

**Comment by brighton818** [comment]
Yes, because we need more helps from other students.

**Comment by jackivan88** [comment]
OK. I want to limit those projects to things that need to be done in
advance. Things that are done the day of will be covered by the credit for
the event itself.

**Comment by brighton818** [comment]
There are some stretch projects on trello, such as designing a t-shirt, and taking care of expenses.
