### ISSUE TITLE
How will we promote the event?

### ISSUE THREAD

**Issue by jackivan88** [seoul-christian-school/hackathon-one#12]
We need to consider multiple methods of advertising the event, but let's make sure we don't make it harder on ourselves than it needs to be. Keep it simple.

**Comment by brighton818** [comment]
We will ask Miss. Walker for help to promote it or call the schools to promote our event.

**Comment by jackivan88** [comment]
Would it be possible to promote it ourselves through churches and friends,
as well as social networks?

Are there places like subway stations where we can post information?

**Comment by brighton818** [comment]
We will give the flyer to Miss Walker and tell her to advertise and we will also make a flyer in Korean and post it on the streets.
