### ISSUE TITLE
How will you handle delegating specific responsibilities?

### ISSUE THREAD

**Issue by jackivan88** [seoul-christian-school/hackathon-one#13]
All TECH students will be required to attend and assist the day of as part of the course credit. However, who will decide what they do, and how will you decide? You need to make sure tasks are assigned so that each class member bears some responsibility, but you also need to make sure that your classmates take ownership of their tasks. That's easier when they're interested in what they're doing.

**Comment by brighton818** [comment]
We would need different kinds of help and set ups, other students might have to help and we will assign groups for individual task.

**Comment by jackivan88** [comment]
Let's start thinking about things that will need to be done and then we can
assign people to handle them.

**Comment by brighton818** [comment]
Also we will let students know through trello.
