### ISSUE TITLE
Where will we host the hackathon?

### ISSUE THREAD

**Issue by jackivan88** [seoul-christian-school/hackathon-one#2]
What part of the school building makes the most sense for hosting the event? We need to make sure the area we want has excellent wireless coverage, plenty of power outlets, lots of space for tables and chairs, and room to move around.

**Comment by brighton818** [comment]
We will host in the basement where there is no bible studies or any other activities.

**Comment by jackivan88** [comment]
OK @brighton818, what's the power outlet situation like down there?

**Comment by brighton818** [comment]
It's kind of bad. Therefore we need to buy extension cords and set those up.
