### ISSUE TITLE
Will the event cost anything?

### ISSUE THREAD

**Issue by jackivan88** [seoul-christian-school/hackathon-one#3]
Are we going to charge for the hackathon, and if so, what will the fee cover? If we don't charge, will we need to ask for funds from the administration? Also, how will we make sure the money is recorded properly and secured?

**Comment by brighton818** [comment]
Yes, we should make people pay at least 5000 won in order to provide food and for the space, area.

**Comment by brighton818** [comment]
It changed to 10000 won.
