### ISSUE TITLE
How long will the hackathon last?

### ISSUE THREAD

**Issue by jackivan88** [seoul-christian-school/hackathon-one#4]
We want to make sure it's long enough to accomplish plenty of work, but not so long that people get bored and leave. An exception might be if it's an "open house" style event, but then it needs to be staffed properly for the entire event.

**Comment by brighton818** [comment]
It will last for 4 hours.

**Comment by davidjanghoonlee** [comment]
4 - 6 hours

**Comment by brighton818** [comment]
It changed to 8 hours.

**Comment by brighton818** [comment]
It again changed to 6 hours.
