### ISSUE TITLE
Who is the target audience?

### ISSUE THREAD

**Issue by jackivan88** [seoul-christian-school/hackathon-one#5]
Who do we want to attend? I definitely want to see the event promoted within the school, but I'd also like to see plenty of people from the neighborhood as well as friends and family of TECH students who are interested. But we need to understand what kind of person we are expecting to attend so that we can plan the events appropriately.

**Comment by davidjanghoonlee** [comment]
Mature students who are interested in programming and who are not beginners.

**Comment by jackivan88** [comment]
OK, so how do we measure that @davidjanghoonlee?

**Comment by Paul-I** [comment]
Both mature and beginners in tech are welcome to come.
