### ISSUE TITLE
Will we provide food?

### ISSUE THREAD

**Issue by jackivan88** [seoul-christian-school/hackathon-one#6]
Especially if the event is longer, we need to decide whether or not we will provide food.

**Comment by davidjanghoonlee** [comment]
Yes, definitely! We will ask our parents for support.

**Comment by jackivan88** [comment]
Are you thinking it will be more like snack setup where people just go get something when they're hungry or that we will seat down and eat at a certain time?

**Comment by brighton818** [comment]
We will buy pizzas and other snacks and put them on a table and let people just grab one of those when they want to have them.
